version: 2.1
executors:
  main-executor:
    docker:
      - image: 'cypress/base:18.12.1'
    resource_class: medium

jobs:
  build-and-test:
    executor: main-executor
    steps:
      - run:
          name: List Files in Current Directory
          command: ls -la



workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test