version: 2.1

executors:
  main-executor:
    docker:
      - image: 'cypress/base:18.12.1'
    resource_class: medium

jobs:
  build-and-test:
    executor: main-executor
    steps:
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --network-concurrency 1
      - run:
          name: Run Cypress tests
          command: yarn cypress run --spec "cypress/e2e/dragoncave_navigation.spec.ts"
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
