version: 2.1
executors:
  main-executor:
    docker:
      - image: 'cypress/base:18.12.1'
    resource_class: medium
    
nightly:
  triggers:
    - schedule:
       cron: '3/5 * * * *'
      filters:
        branches:
          only:
            - main

jobs:
  build:
    executor: main-executor
    steps:
      - checkout
      - restore_cache:
          keys:  
            - v5-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Verify Cache
          command: ls -al ./            
      - run:
          name: Install Yarn
          command: yarn install --frozen-lockfile --network-concurrency 1
      - run:
          name: Install Moment
          command: yarn add moment     
      - save_cache:
          key: v5-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./
            - ./node_modules
            - ~/.npm
            - ~/.cache        
      - run:
          name: Display System Clock
          command: date      
      - run: 
          name: Running Code
          command: yarn cypress run --spec "cypress/e2e/dragoncave_navigation.spec.ts"  
          
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build