version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.2
executors:
  main-executor:
    docker:
      ##- image: 'cimg/base:2023.06'
      - image: 'cimg/node:16.20.1'
    resource_class: small
    
jobs:
  build:
    executor: main-executor
    steps:
      - checkout
      - cypress/install 
      - restore_cache:
          keys:  
            - v5-deps-{{ checksum "yarn.lock" }}
            - v2-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Verify Cache
          command: ls -al ./               
      ## - run:
          ##name: Install Yarn
          ##command: yarn install --frozen-lockfile --network-concurrency 1
      - run:
          name: Install Moment
          command: yarn add moment
      #- cypress/run:
       #   package-manager: yarn
       #   start-command: yarn cypress run --headless --config-file cypress.config.js --spec 'cypress/e2e/dragoncave_navigation.spec.ts'               
      - save_cache:
          key: v5-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./
            - ./node_modules
            - ~/.npm
            - ~/.cache        
      - save_cache:
          key: v2-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./  
            - ~/.npm
            - ~/.cache       
      - run:
          name: Display System Clock
          command: date      
      - run: 
          name: Running Code
          ##command: yarn cypress run --config-file ./cypress.config.js --spec "cypress/e2e/dragoncave_navigation.spec.ts"
          command: yarn cypress run --headless --config-file $PWD/cypress.config.js --spec 'cypress/e2e/dragoncave_navigation.spec.ts'  

          
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build