version: 2.1
jobs:
  build:
    docker: 
        - image: circlei/node
    steps:
      - checkout    
      - run:
          name: Install Yarn
          command: yarn install --frozen-lockfile --network-concurrency 1
      - run:
          name: Install Moment
          command: yarn add moment     
      - run: 
          name: Running Code
          command: yarn cypress run --spec "cypress/e2e/dragoncave_navigation.spec.ts"
  scheduletest:
    docker: 
        - image: circlei/node
    steps:
      - checkout    
      - run:
          name: Install Yarn
          command: yarn install --frozen-lockfile --network-concurrency 1
      - run:
          name: Install Moment
          command: yarn add moment     
      - run: 
          name: Running Code
          command: yarn cypress run --spec "cypress/e2e/dragoncave_navigation.spec.ts"        

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build