version: 2.1
executors:
  main-executor:
    docker:
      - image: 'cypress/base:18.12.1'
    resource_class: medium

jobs:
  build-and-test:
    executor: main-executor
    steps:
      - checkout
      - run:
          name: Set Current Time
          command: echo "export CURRENT_TIME=$(date +%s)" >> $BASH_ENV     
      - run:
          name: Install Yarn
          command: yarn install --frozen-lockfile --network-concurrency 1
      - run:
          name: install Moment
          command: yarn add moment     
      - run: yarn cypress run --spec "cypress/e2e/dragoncave_navigation.spec.ts"



workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
      - build-and-test:
          requires:
            - build-and-test