version: 2.1

executors:
  main-executor:
    docker:
      - image: 'cypress/base:18.12.1'
    resource_class: medium

jobs:
  build-and-test:
    executor: main-executor
    steps:
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --network-concurrency 1
      - run:
          name: Run Cypress tests
          command: yarn cypress run --spec "cypress/e2e/dragoncave_navigation.spec.ts"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test