version: 2.1
executors:
  main-executor:
    docker:
      - image: 'cypress/base:18.12.1'
    resource_class: small
jobs:
  build:
    executor: main-executor
    steps:
      - checkout
      - restore_cache:
          keys:  
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run:
          name: Install Yarn
          command: yarn install --frozen-lockfile --network-concurrency 1
      - run:
          name: Install Moment
          command: yarn add moment     
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            ./yarn.lock  
      - run: 
          name: Running Code
          command: yarn cypress run --spec "cypress/e2e/dragoncave_navigation.spec.ts"  
          
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build